### ISSUE TITLE
Show that the server is offline

### ISSUE THREAD

**Issue by Doxify** [emilianomaccaferri/query#1]
Currently, if you query a server that's offline no error is thrown, can you throw an error when the server is offline?

**Comment by emilianomaccaferri** [comment]
yeah sure, I'll add it tonight

**Comment by emilianomaccaferri** [comment]
functionality added
check [19f568d](https://github.com/emilianomaccaferri/minecraft-query/commit/19f568dd9fd85d39d6236a64a40c2c55bf5e8cca)

run `npm install minecraft-query@latest` to update
