### ISSUE TITLE
Separate comma players.

### ISSUE THREAD

**Issue by zkita** [emilianomaccaferri/query#12]
Is there any way to separate the players by a space after the comma, when placed in an embed they all appear together.

![image](https://user-images.githubusercontent.com/36092786/158681598-9c2b8c87-cf24-49b2-9b98-9fb31595a26c.png)

**Comment by emilianomaccaferri** [comment]
since "players" is an array you just need to do `players.join(", ")`

**Comment by zkita** [comment]
> since "players" is an array you just need to do `players.join(", ")`

Thank you, I didn't know 😅
