### ISSUE TITLE
Error while query

### ISSUE THREAD

**Issue by dadodasyra** [emilianomaccaferri/query#6]
(node:15348) UnhandledPromiseRejectionWarning: Error: Challenge token generation timeout: 172.65.216.245
    at Timeout._onTimeout (c:\Users\rszur\node_modules\minecraft-query\Query.js:149:28)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)

It is the hypixel ip, also doesn't work with my private server

**Comment by emilianomaccaferri** [comment]
have you opened the query port?
have you enabled the query option in `server.properties`?

hypixel doesn't expose the query port to the public for obvious reasons.

**Comment by dadodasyra** [comment]
Yes query option is enabled on my server.

**Comment by alex-r89** [comment]
I am getting the same.

The query port is the default port for hypixel, hence why server lists like https://minecraftservers.org/ can query them (https://minecraftservers.org/server/221843).

To further validate this, I can prove the query port for hypixel is default by using this tool: https://api.mcsrvstat.us/2/mc.hypixel.net

There is some bug with this package. It doesn't seem to work querying servers.

**Comment by alex-r89** [comment]
I am getting the same.

I am unsure how the query works, but using the default query port (25565) should work for hypixel.

To validate this, using mcsrvstat with the default port returns data: https://api.mcsrvstat.us/2/mc.hypixel.net:25565
This is also how server lists are querying the server work (see https://minecraftservers.org/server/221843)

There is some bug with this package. It doesn't seem to work querying servers using the default port.

**Comment by emilianomaccaferri** [comment]
how do you reproduce the error?

**Comment by emilianomaccaferri** [comment]
You should check your configuration for errors.
This is a working example using the default port (hosted on my server):
```
const Query = require("minecraft-query");

const q = new Query({host: 'emilianomaccaferri.com', port: 25565, timeout: 7500});

q.fullStat()
  .then(success => {

    console.log(success);

    return q.basicStat()

  })

  .then(success => {

    console.log(success);

    q.close();

})

```
Hypixel does not respond because it doesnt have query enabled. mcsrvstat.us simply *pings* the server instead of *querying* it (the api responds with the protocol code 47, which stands for ping).
See https://mcsrvstat.us/server/mc.hypixel.net (says Query: No).
Let me know if you still encounter errors!
